<a href="https://colab.research.google.com/github/VIAMRSH123/ML-Lab/blob/main/Lab-0/Housing_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab-0

In [4]:
import pandas as pd
from IPython.display import display

pd.set_option("display.float_format", "{:,.2f}".format)

df = pd.read_csv("housing.csv")

print("\n" + "="*30)
print("DATAFRAME INFO")
print("="*30)
df.info()

print("\n" + "="*30)
print("DESCRIPTIVE STATISTICS")
print("="*30)
display(df.describe())

print("\n" + "="*30)
print("OCEAN PROXIMITY COUNTS")
print("="*30)
display(df["ocean_proximity"].value_counts().to_frame("count"))

print("\n" + "="*30)
print("MISSING VALUES")
print("="*30)
missing = df.isnull().sum()
display(missing[missing > 0].to_frame("missing_count"))

==============================
DATAFRAME INFO
==============================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

==============================
DESCRIPTIVE STATISTICS
==============================

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,"20,640.00","20,640.00","20,640.00","20,640.00","20,433.00","20,640.00","20,640.00","20,640.00","20,640.00"
mean,-119.57,35.63,28.64,"2,635.76",537.87,"1,425.48",499.54,3.87,"206,855.82"
std,2.00,2.14,12.59,"2,181.62",421.39,"1,132.46",382.33,1.90,"115,395.62"
min,-124.35,32.54,1.00,2.00,1.00,3.00,1.00,0.50,"14,999.00"
25%,-121.80,33.93,18.00,"1,447.75",296.00,787.00,280.00,2.56,"119,600.00"
50%,-118.49,34.26,29.00,"2,127.00",435.00,"1,166.00",409.00,3.53,"179,700.00"
75%,-118.01,37.71,37.00,"3,148.00",647.00,"1,725.00",605.00,4.74,"264,725.00"
max,-114.31,41.95,52.00,"39,320.00","6,445.00","35,682.00","6,082.00",15.00,"500,001.00"

==============================
OCEAN PROXIMITY COUNTS
==============================

                 count
ocean_proximity
<1H OCEAN         9136
INLAND            6551
NEAR OCEAN        2658
NEAR BAY          2290
ISLAND               5

==============================
MISSING VALUES
==============================

                missing_count
total_bedrooms            207